version: '3.8'

services:
  ergoquipt-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ergoquipt-admin-web
    ports:
      - "3001:80"
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
      - REACT_APP_API_URL=https://ergoquipt.inkubasistartupunhas.id/api/v1
    restart: unless-stopped
    networks:
      - ergoquipt-network

  ergoquipt-admin-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ergoquipt-admin-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=https://ergoquipt.inkubasistartupunhas.id/api/v1
    stdin_open: true
    tty: true
    networks:
      - ergoquipt-network

networks:
  ergoquipt-network:
    driver: bridge